// Generated by scripts/release/release.mjs. Do not edit by hand.
export const mobileReleaseProfile = {
  name: 'global-prod',
  market: 'global',
  review: false,
  apiBaseUrl: 'https://global-api.vividrop.cn',
} as const;

export const releaseApiBaseUrl = mobileReleaseProfile.apiBaseUrl.trim() || null;
