// Objective-C API for talking to github.com/nicksyncflow/sidecar/mobiletunnel Go package.
//   gobind -lang=objc github.com/nicksyncflow/sidecar/mobiletunnel
//
// File is generated by gobind. Do not edit.

#ifndef __Mobiletunnel_H__
#define __Mobiletunnel_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobiletunnelTunnel;

@interface MobiletunnelTunnel : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (void)stop;
@end

/**
 * CurrentSelectedICERoute returns the active tunnel's selected ICE route.
It returns an empty string until the tunnel has selected a candidate pair.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobiletunnelCurrentSelectedICERoute(void);

/**
 * StartTunnel runs the WebRTC + Yamux tunnel and returns the local TCP port it listens on.
If it fails, it returns -1.
 */
FOUNDATION_EXPORT long MobiletunnelStartTunnel(NSString* _Nullable signalingURL, NSString* _Nullable clientID, NSString* _Nullable targetClientID, NSString* _Nullable token, NSString* _Nullable pairingToken, NSString* _Nullable iceServersJSON);

/**
 * StopTunnel stops the currently running P2P tunnel.
 */
FOUNDATION_EXPORT void MobiletunnelStopTunnel(void);

/**
 * TakeDiagnosticsLog returns buffered mobile tunnel diagnostics and clears the buffer.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobiletunnelTakeDiagnosticsLog(void);

#endif
