# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

ENV['RCT_USE_PREBUILT_RNCORE'] = '0'

target 'SyncFlowMobile' do
  config = use_native_modules!
  hermes_cli_path = '${PODS_ROOT}/hermes-engine/destroot/bin/hermesc'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'SSZipArchive', '~> 2.4'

  # react-native-iap requires RCT-Folly when new arch is enabled, but RN 0.76+
  # uses prebuilt ReactNativeDependencies and does not install RCT-Folly by default.
  # Explicitly include RCT-Folly and its transitive deps so that RNIap.podspec
  # can resolve the dependency without building all of RN from source.
  rn_path = config[:reactNativePath]
  pod 'boost', :podspec => "#{rn_path}/third-party-podspecs/boost.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'fast_float', :podspec => "#{rn_path}/third-party-podspecs/fast_float.podspec"
  pod 'fmt', :podspec => "#{rn_path}/third-party-podspecs/fmt.podspec"
  pod 'RCT-Folly', :podspec => "#{rn_path}/third-party-podspecs/RCT-Folly.podspec", :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end

    installer.aggregate_targets
      .map(&:user_project)
      .uniq
      .each do |project|
        project.native_targets.each do |target|
          target.build_configurations.each do |build_configuration|
            build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
            build_configuration.build_settings['HERMES_CLI_PATH'] = hermes_cli_path
          end
        end
        project.save
      end
  end
end
