export const ErrorCode = {
  PAIR_CODE_INVALID: 'PAIR_CODE_INVALID',
  PAIRING_CODE_INVALID: 'PAIRING_CODE_INVALID',
  PAIRING_CLIENT_BLOCKED: 'PAIRING_CLIENT_BLOCKED',
  PAIR_TOKEN_INVALID: 'PAIR_TOKEN_INVALID',
  PROTO_VERSION_UNSUPPORTED: 'PROTO_VERSION_UNSUPPORTED',
  APP_VERSION_INCOMPATIBLE: 'APP_VERSION_INCOMPATIBLE',
  FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
  LOW_DISK_PAUSED: 'LOW_DISK_PAUSED',
  RECEIVE_ROOT_MISSING: 'RECEIVE_ROOT_MISSING',
  LOCAL_NETWORK_DENIED: 'LOCAL_NETWORK_DENIED',
  PHOTO_PERMISSION_DENIED: 'PHOTO_PERMISSION_DENIED',
  TARGET_NOT_FOUND: 'TARGET_NOT_FOUND',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
  RESUME_NOT_AVAILABLE: 'RESUME_NOT_AVAILABLE',
  SHARE_NOT_READY: 'SHARE_NOT_READY',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
