export interface CountryCodeInfo {
  code: string;        // Phone prefix (e.g. "+86")
  iso: string;         // ISO 3166-1 alpha-2 (e.g. "CN")
  nameEn: string;      // English name (e.g. "China")
  nameZh: string;      // Chinese name (e.g. "中国")
  flag: string;        // Flag emoji (e.g. "🇨🇳")
  minLength: number;   // Minimum phone length
  maxLength: number;   // Maximum phone length
}

export const COUNTRY_CODES: CountryCodeInfo[] = [
  { code: '+86', iso: 'CN', nameEn: 'China', nameZh: '中国', flag: '🇨🇳', minLength: 11, maxLength: 11 },
  { code: '+1', iso: 'US', nameEn: 'United States', nameZh: '美国', flag: '🇺🇸', minLength: 10, maxLength: 10 },
  { code: '+1', iso: 'CA', nameEn: 'Canada', nameZh: '加拿大', flag: '🇨🇦', minLength: 10, maxLength: 10 },
  { code: '+44', iso: 'GB', nameEn: 'United Kingdom', nameZh: '英国', flag: '🇬🇧', minLength: 9, maxLength: 10 },
  { code: '+81', iso: 'JP', nameEn: 'Japan', nameZh: '日本', flag: '🇯🇵', minLength: 9, maxLength: 10 },
  { code: '+82', iso: 'KR', nameEn: 'South Korea', nameZh: '韩国', flag: '🇰🇷', minLength: 9, maxLength: 10 },
  { code: '+65', iso: 'SG', nameEn: 'Singapore', nameZh: '新加坡', flag: '🇸🇬', minLength: 8, maxLength: 8 },
  { code: '+852', iso: 'HK', nameEn: 'Hong Kong', nameZh: '中国香港', flag: '🇭🇰', minLength: 8, maxLength: 8 },
  { code: '+886', iso: 'TW', nameEn: 'Taiwan', nameZh: '中国台湾', flag: '🇹🇼', minLength: 9, maxLength: 9 },
  { code: '+853', iso: 'MO', nameEn: 'Macau', nameZh: '中国澳门', flag: '🇲🇴', minLength: 8, maxLength: 8 },
  { code: '+61', iso: 'AU', nameEn: 'Australia', nameZh: '澳大利亚', flag: '🇦🇺', minLength: 9, maxLength: 9 },
  { code: '+49', iso: 'DE', nameEn: 'Germany', nameZh: '德国', flag: '🇩🇪', minLength: 10, maxLength: 11 },
  { code: '+33', iso: 'FR', nameEn: 'France', nameZh: '法国', flag: '🇫🇷', minLength: 9, maxLength: 9 },
  { code: '+91', iso: 'IN', nameEn: 'India', nameZh: '印度', flag: '🇮🇳', minLength: 10, maxLength: 10 },
  { code: '+60', iso: 'MY', nameEn: 'Malaysia', nameZh: '马来西亚', flag: '🇲🇾', minLength: 9, maxLength: 10 },
  { code: '+62', iso: 'ID', nameEn: 'Indonesia', nameZh: '印度尼西亚', flag: '🇮🇩', minLength: 9, maxLength: 12 },
  { code: '+63', iso: 'PH', nameEn: 'Philippines', nameZh: '菲律宾', flag: '🇵🇭', minLength: 10, maxLength: 10 },
  { code: '+66', iso: 'TH', nameEn: 'Thailand', nameZh: '泰国', flag: '🇹🇭', minLength: 9, maxLength: 9 },
  { code: '+84', iso: 'VN', nameEn: 'Vietnam', nameZh: '越南', flag: '🇻🇳', minLength: 9, maxLength: 9 },
  { code: '+39', iso: 'IT', nameEn: 'Italy', nameZh: '意大利', flag: '🇮🇹', minLength: 9, maxLength: 10 },
  { code: '+34', iso: 'ES', nameEn: 'Spain', nameZh: '西班牙', flag: '🇪🇸', minLength: 9, maxLength: 9 },
  { code: '+41', iso: 'CH', nameEn: 'Switzerland', nameZh: '瑞士', flag: '🇨🇭', minLength: 9, maxLength: 9 },
  { code: '+31', iso: 'NL', nameEn: 'Netherlands', nameZh: '荷兰', flag: '🇳🇱', minLength: 9, maxLength: 9 },
  { code: '+32', iso: 'BE', nameEn: 'Belgium', nameZh: '比利时', flag: '🇧🇪', minLength: 9, maxLength: 9 },
  { code: '+46', iso: 'SE', nameEn: 'Sweden', nameZh: '瑞典', flag: '🇸🇪', minLength: 7, maxLength: 9 },
  { code: '+47', iso: 'NO', nameEn: 'Norway', nameZh: '挪威', flag: '🇳🇴', minLength: 8, maxLength: 8 },
  { code: '+45', iso: 'DK', nameEn: 'Denmark', nameZh: '丹麦', flag: '🇩🇰', minLength: 8, maxLength: 8 },
  { code: '+358', iso: 'FI', nameEn: 'Finland', nameZh: '芬兰', flag: '🇫🇮', minLength: 5, maxLength: 10 },
  { code: '+971', iso: 'AE', nameEn: 'United Arab Emirates', nameZh: '阿联酋', flag: '🇦🇪', minLength: 9, maxLength: 9 },
  { code: '+966', iso: 'SA', nameEn: 'Saudi Arabia', nameZh: '沙特阿拉伯', flag: '🇸🇦', minLength: 9, maxLength: 9 },
  { code: '+27', iso: 'ZA', nameEn: 'South Africa', nameZh: '南非', flag: '🇿🇦', minLength: 9, maxLength: 9 },
  { code: '+7', iso: 'RU', nameEn: 'Russia', nameZh: '俄罗斯', flag: '🇷🇺', minLength: 10, maxLength: 10 },
  { code: '+55', iso: 'BR', nameEn: 'Brazil', nameZh: '巴西', flag: '🇧🇷', minLength: 10, maxLength: 11 },
  { code: '+52', iso: 'MX', nameEn: 'Mexico', nameZh: '墨西哥', flag: '🇲🇽', minLength: 10, maxLength: 10 },
  { code: '+64', iso: 'NZ', nameEn: 'New Zealand', nameZh: '新西兰', flag: '🇳🇿', minLength: 8, maxLength: 10 },
  { code: '+353', iso: 'IE', nameEn: 'Ireland', nameZh: '爱尔兰', flag: '🇮🇪', minLength: 9, maxLength: 9 },
  { code: '+90', iso: 'TR', nameEn: 'Turkey', nameZh: '土耳其', flag: '🇹🇷', minLength: 10, maxLength: 10 },
  { code: '+48', iso: 'PL', nameEn: 'Poland', nameZh: '波兰', flag: '🇵🇱', minLength: 9, maxLength: 9 },
  { code: '+351', iso: 'PT', nameEn: 'Portugal', nameZh: '葡萄牙', flag: '🇵🇹', minLength: 9, maxLength: 9 },
  { code: '+30', iso: 'GR', nameEn: 'Greece', nameZh: '希腊', flag: '🇬🇷', minLength: 10, maxLength: 10 },
  { code: '+43', iso: 'AT', nameEn: 'Austria', nameZh: '奥地利', flag: '🇦🇹', minLength: 10, maxLength: 13 },
  { code: '+352', iso: 'LU', nameEn: 'Luxembourg', nameZh: '卢森堡', flag: '🇱🇺', minLength: 9, maxLength: 9 },
  { code: '+972', iso: 'IL', nameEn: 'Israel', nameZh: '以色列', flag: '🇮🇱', minLength: 9, maxLength: 9 },
  { code: '+54', iso: 'AR', nameEn: 'Argentina', nameZh: '阿根廷', flag: '🇦🇷', minLength: 10, maxLength: 10 },
  { code: '+56', iso: 'CL', nameEn: 'Chile', nameZh: '智利', flag: '🇨🇱', minLength: 9, maxLength: 9 },
  { code: '+57', iso: 'CO', nameEn: 'Colombia', nameZh: '哥伦比亚', flag: '🇨🇴', minLength: 10, maxLength: 10 },
  { code: '+51', iso: 'PE', nameEn: 'Peru', nameZh: '秘鲁', flag: '🇵🇪', minLength: 9, maxLength: 9 },
  { code: '+92', iso: 'PK', nameEn: 'Pakistan', nameZh: '巴基斯坦', flag: '🇵🇰', minLength: 10, maxLength: 10 },
  { code: '+880', iso: 'BD', nameEn: 'Bangladesh', nameZh: '孟加拉国', flag: '🇧🇩', minLength: 10, maxLength: 10 },
  { code: '+20', iso: 'EG', nameEn: 'Egypt', nameZh: '埃及', flag: '🇪🇬', minLength: 10, maxLength: 10 },
  { code: '+234', iso: 'NG', nameEn: 'Nigeria', nameZh: '尼日利亚', flag: '🇳🇬', minLength: 10, maxLength: 10 },
  { code: '+254', iso: 'KE', nameEn: 'Kenya', nameZh: '肯尼亚', flag: '🇰🇪', minLength: 9, maxLength: 9 },
  { code: '+216', iso: 'TN', nameEn: 'Tunisia', nameZh: '突尼斯', flag: '🇹🇳', minLength: 8, maxLength: 8 },
  { code: '+212', iso: 'MA', nameEn: 'Morocco', nameZh: '摩洛哥', flag: '🇲🇦', minLength: 9, maxLength: 9 },
  { code: '+380', iso: 'UA', nameEn: 'Ukraine', nameZh: '乌克兰', flag: '🇺🇦', minLength: 9, maxLength: 9 },
  { code: '+40', iso: 'RO', nameEn: 'Romania', nameZh: '罗马尼亚', flag: '🇷🇴', minLength: 9, maxLength: 9 },
  { code: '+36', iso: 'HU', nameEn: 'Hungary', nameZh: '匈牙利', flag: '🇭🇺', minLength: 9, maxLength: 9 },
  { code: '+420', iso: 'CZ', nameEn: 'Czechia', nameZh: '捷克', flag: '🇨🇿', minLength: 9, maxLength: 9 },
  { code: '+421', iso: 'SK', nameEn: 'Slovakia', nameZh: '斯洛伐克', flag: '🇸🇰', minLength: 9, maxLength: 9 },
  { code: '+359', iso: 'BG', nameEn: 'Bulgaria', nameZh: '保加利亚', flag: '🇧🇬', minLength: 8, maxLength: 9 },
  { code: '+385', iso: 'HR', nameEn: 'Croatia', nameZh: '克罗地亚', flag: '🇭🇷', minLength: 8, maxLength: 9 },
];
