
// Objective-C API for talking to the following Go packages
//
//	github.com/nicksyncflow/sidecar/mobiletunnel
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SyncFlowMobileTunnel_FRAMEWORK_H__
#define __SyncFlowMobileTunnel_FRAMEWORK_H__

#include "Mobiletunnel.objc.h"
#include "Universe.objc.h"

#endif
