import type {
  DashboardDeviceDTO,
  DesktopAccessRecordDTO,
  DesktopManagedDeviceDTO,
  ReceivedLibraryItemDTO,
} from '@syncflow/contracts';

export function shouldUsePreviewData(hasRealData: boolean): boolean {
  return import.meta.env.DEV && !hasRealData;
}

export const previewManagedDevices: DesktopManagedDeviceDTO[] = [
  {
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    clientIdShort: 'iphone-15',
    displayName: 'iPhone 15 Pro',
    platform: 'iOS',
    stableDeviceId: 'iphone-15-pro',
    lastIp: '192.168.1.106',
    authorizedAt: '2026-06-10T08:20:00Z',
    lastSeenAt: '2026-06-15T10:42:00Z',
    authorizationStatus: 'authorized',
    blockStatus: 'none',
    failedAttemptCount: 0,
    todayFileCount: 8,
    todayBytes: 3456102400,
    totalFileCount: 172,
    totalBytes: 52219011072,
  },
  {
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-galaxy-s24-ultra',
    clientIdShort: 'galaxy-s24',
    displayName: 'Galaxy S24 Ultra',
    platform: 'Android',
    stableDeviceId: 'galaxy-s24-ultra',
    lastIp: '192.168.1.112',
    authorizedAt: '2026-06-09T12:04:00Z',
    lastSeenAt: '2026-06-15T09:18:00Z',
    authorizationStatus: 'authorized',
    blockStatus: 'none',
    failedAttemptCount: 0,
    todayFileCount: 3,
    todayBytes: 1429200896,
    totalFileCount: 94,
    totalBytes: 31274287104,
  },
  {
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-ipad-pro',
    clientIdShort: 'ipad-pro',
    displayName: 'iPad Pro',
    platform: 'iPadOS',
    stableDeviceId: 'ipad-pro',
    lastIp: '192.168.1.118',
    authorizedAt: '2026-06-08T18:12:00Z',
    lastSeenAt: '2026-06-14T18:20:00Z',
    authorizationStatus: 'authorized',
    blockStatus: 'none',
    failedAttemptCount: 1,
    todayFileCount: 0,
    todayBytes: 0,
    totalFileCount: 38,
    totalBytes: 9126805504,
  },
  {
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-blocked-iphone',
    clientIdShort: 'blocked-iphone',
    displayName: '备用 iPhone',
    platform: 'iOS',
    stableDeviceId: 'backup-iphone',
    lastIp: '192.168.1.120',
    authorizedAt: '2026-06-06T09:00:00Z',
    lastSeenAt: '2026-06-13T21:31:00Z',
    authorizationStatus: 'revoked',
    blockStatus: 'active',
    failedAttemptCount: 5,
    blockedAt: '2026-06-13T21:32:00Z',
    blockReason: 'too_many_failed_attempts',
    todayFileCount: 0,
    todayBytes: 0,
    totalFileCount: 17,
    totalBytes: 3072327680,
  },
];

export const previewDashboardDevices: DashboardDeviceDTO[] = [
  {
    deviceId: 'preview-iphone-15-pro',
    stableDeviceId: 'preview-iphone-15-pro',
    displayName: 'iPhone 15 Pro',
    clientName: 'iPhone 15 Pro',
    platform: 'iOS',
    ip: '192.168.1.106',
    status: 'transferring',
    todayFileCount: 8,
    todayBytes: 3456102400,
    storageLeft: '66.6 GB',
    storagePath: '/Users/vividrop/Receive',
    devicePath: '/Users/vividrop/Receive/iPhone 15 Pro',
    currentFile: {
      filename: 'IMG_20260610_Office.mov',
      progress: 64,
      fileSize: 3435973836,
    },
  },
  {
    deviceId: 'preview-galaxy-s24-ultra',
    stableDeviceId: 'preview-galaxy-s24-ultra',
    displayName: 'Galaxy S24 Ultra',
    clientName: 'Galaxy S24 Ultra',
    platform: 'Android',
    ip: '192.168.1.112',
    status: 'connected_idle',
    todayFileCount: 3,
    todayBytes: 1429200896,
    storageLeft: '88.2 GB',
    storagePath: '/Users/vividrop/Receive',
    devicePath: '/Users/vividrop/Receive/Galaxy S24 Ultra',
  },
];

export const previewReceivedLibraryItems: ReceivedLibraryItemDTO[] = [
  {
    resourceId: 'preview-rec-1',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    displayName: 'IMG_20260610_Office.mov',
    fileKey: 'preview-key-1',
    filename: 'IMG_20260610_Office.mov',
    mediaType: 'video/quicktime',
    fileSize: 3435973836,
    completedAt: '2026-06-15T10:42:00Z',
    shareStatus: 'not_shared',
  },
  {
    resourceId: 'preview-rec-2',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    displayName: 'IMG_8493.HEIC',
    fileKey: 'preview-key-2',
    filename: 'IMG_8493.HEIC',
    mediaType: 'image/heic',
    fileSize: 12582912,
    completedAt: '2026-06-15T10:16:00Z',
    shareStatus: 'not_shared',
  },
  {
    resourceId: 'preview-rec-3',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-galaxy-s24-ultra',
    displayName: 'Market_visit_notes.pdf',
    fileKey: 'preview-key-3',
    filename: 'Market_visit_notes.pdf',
    mediaType: 'application/pdf',
    fileSize: 3565158,
    completedAt: '2026-06-15T09:32:00Z',
    shareStatus: 'shared',
  },
  {
    resourceId: 'preview-rec-4',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-galaxy-s24-ultra',
    displayName: 'Expense_receipts.zip',
    fileKey: 'preview-key-4',
    filename: 'Expense_receipts.zip',
    mediaType: 'application/zip',
    fileSize: 134217728,
    completedAt: '2026-06-15T09:30:00Z',
    shareStatus: 'not_shared',
  },
  {
    resourceId: 'preview-rec-5',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-ipad-pro',
    displayName: 'Presentation_annotations.pdf',
    fileKey: 'preview-key-5',
    filename: 'Presentation_annotations.pdf',
    mediaType: 'application/pdf',
    fileSize: 9542041,
    completedAt: '2026-06-14T18:20:00Z',
    shareStatus: 'not_shared',
  },
];

export const previewAccessRecords: DesktopAccessRecordDTO[] = [
  {
    recordId: 'preview-access-1',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    displayName: 'iPhone 15 Pro',
    resourceId: 'preview-shared-1',
    resourceKind: 'received_file',
    resourceName: '产品需求文档v3.pdf',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-15T10:40:00Z',
  },
  {
    recordId: 'preview-access-2',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    displayName: 'iPhone 15 Pro',
    resourceId: 'preview-shared-2',
    resourceKind: 'received_file',
    resourceName: '团队合照.jpg',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-15T10:41:00Z',
  },
  {
    recordId: 'preview-access-3',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-galaxy-s24-ultra',
    displayName: 'Galaxy S24 Ultra',
    resourceId: 'preview-shared-3',
    resourceKind: 'shared_file',
    resourceName: '旅行计划.xlsx',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-15T09:28:00Z',
  },
  {
    recordId: 'preview-access-4',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-ipad-pro',
    displayName: 'iPad Pro',
    resourceId: 'preview-shared-4',
    resourceKind: 'shared_folder',
    resourceName: '季度汇报.pptx',
    action: 'view',
    result: 'ok',
    accessedAt: '2026-06-14T18:20:00Z',
  },
  {
    recordId: 'preview-access-5',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-blocked-iphone',
    displayName: '备用 iPhone',
    resourceId: 'preview-shared-5',
    resourceKind: 'received_file',
    resourceName: '合同扫描件.pdf',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-13T21:30:00Z',
  },
  {
    recordId: 'preview-access-6',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    displayName: 'iPhone 15 Pro',
    resourceId: 'preview-shared-6',
    resourceKind: 'received_file',
    resourceName: '活动现场.mov',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-12T16:10:00Z',
  },
  {
    recordId: 'preview-access-7',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-galaxy-s24-ultra',
    displayName: 'Galaxy S24 Ultra',
    resourceId: 'preview-shared-7',
    resourceKind: 'received_file',
    resourceName: '报价单.xlsx',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-11T13:42:00Z',
  },
  {
    recordId: 'preview-access-8',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-ipad-pro',
    displayName: 'iPad Pro',
    resourceId: 'preview-shared-8',
    resourceKind: 'shared_folder',
    resourceName: '设计稿归档.zip',
    action: 'view',
    result: 'ok',
    accessedAt: '2026-06-10T11:24:00Z',
  },
  {
    recordId: 'preview-access-9',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-blocked-iphone',
    displayName: '备用 iPhone',
    resourceId: 'preview-shared-9',
    resourceKind: 'received_file',
    resourceName: '会议录音.m4a',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-09T09:08:00Z',
  },
  {
    recordId: 'preview-access-10',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-iphone-15-pro',
    displayName: 'iPhone 15 Pro',
    resourceId: 'preview-shared-10',
    resourceKind: 'received_file',
    resourceName: '门店巡检照片.heic',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-08T20:16:00Z',
  },
  {
    recordId: 'preview-access-11',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-galaxy-s24-ultra',
    displayName: 'Galaxy S24 Ultra',
    resourceId: 'preview-shared-11',
    resourceKind: 'received_file',
    resourceName: '素材清单.csv',
    action: 'download',
    result: 'ok',
    accessedAt: '2026-06-07T18:35:00Z',
  },
  {
    recordId: 'preview-access-12',
    desktopDeviceId: 'preview-desktop',
    clientId: 'preview-ipad-pro',
    displayName: 'iPad Pro',
    resourceId: 'preview-shared-12',
    resourceKind: 'shared_file',
    resourceName: '白板导出.pdf',
    action: 'view',
    result: 'ok',
    accessedAt: '2026-06-06T14:05:00Z',
  },
];
