package store

import (
	"errors"
	"testing"
)

func TestSetGetSetting_Roundtrip(t *testing.T) {
	s := newTestStore(t)

	if err := s.SetSetting("my_key", "my_value"); err != nil {
		t.Fatalf("SetSetting: %v", err)
	}

	val, err := s.GetSetting("my_key")
	if err != nil {
		t.Fatalf("GetSetting: %v", err)
	}
	if val != "my_value" {
		t.Errorf("expected 'my_value', got %q", val)
	}
}

func TestSetSetting_Overwrite(t *testing.T) {
	s := newTestStore(t)

	if err := s.SetSetting("k", "v1"); err != nil {
		t.Fatalf("SetSetting: %v", err)
	}
	if err := s.SetSetting("k", "v2"); err != nil {
		t.Fatalf("SetSetting overwrite: %v", err)
	}

	val, err := s.GetSetting("k")
	if err != nil {
		t.Fatalf("GetSetting: %v", err)
	}
	if val != "v2" {
		t.Errorf("expected 'v2', got %q", val)
	}
}

func TestGetSetting_NotFound(t *testing.T) {
	s := newTestStore(t)

	_, err := s.GetSetting("nonexistent")
	if !errors.Is(err, ErrNoRows) {
		t.Errorf("expected ErrNoRows, got %v", err)
	}
}

func TestGetConnectionCode_AfterMigration(t *testing.T) {
	s := newTestStore(t)

	code, err := s.GetConnectionCode()
	if err != nil {
		t.Fatalf("GetConnectionCode: %v", err)
	}
	if code != "000000" {
		t.Errorf("expected '000000', got %q", code)
	}
}

func TestSetConnectionCode(t *testing.T) {
	s := newTestStore(t)

	if err := s.SetConnectionCode("123456"); err != nil {
		t.Fatalf("SetConnectionCode: %v", err)
	}

	code, err := s.GetConnectionCode()
	if err != nil {
		t.Fatalf("GetConnectionCode: %v", err)
	}
	if code != "123456" {
		t.Errorf("expected '123456', got %q", code)
	}
}

func TestSetConnectionCodeKeepsAuthorizedDevices(t *testing.T) {
	s := newTestStore(t)
	for _, id := range []string{"client-a", "client-b"} {
		if err := s.UpsertPairedDevice(sampleDevice(id)); err != nil {
			t.Fatalf("UpsertPairedDevice %q: %v", id, err)
		}
	}

	if err := s.SetConnectionCode("654321"); err != nil {
		t.Fatalf("SetConnectionCode: %v", err)
	}

	code, err := s.GetConnectionCode()
	if err != nil {
		t.Fatalf("GetConnectionCode: %v", err)
	}
	if code != "654321" {
		t.Fatalf("expected code 654321, got %q", code)
	}

	for _, id := range []string{"client-a", "client-b"} {
		got, err := s.GetPairedDevice(id)
		if err != nil {
			t.Fatalf("GetPairedDevice %q: %v", id, err)
		}
		if got.RevokedAt != nil {
			t.Fatalf("expected %q to remain authorized, revoked_at=%q", id, *got.RevokedAt)
		}
	}
}

func TestGetDeviceID_AfterMigration(t *testing.T) {
	s := newTestStore(t)

	id, err := s.GetDeviceID()
	if err != nil {
		t.Fatalf("GetDeviceID: %v", err)
	}
	// device_id is generated by randomblob, should be non-empty and contain a dash
	if len(id) == 0 {
		t.Error("expected device_id to be non-empty")
	}
	if len(id) < 5 {
		t.Errorf("expected device_id to be at least 5 chars, got %q", id)
	}
}

func TestSetGetDeviceName(t *testing.T) {
	s := newTestStore(t)

	if err := s.SetDeviceName("My Mac Pro"); err != nil {
		t.Fatalf("SetDeviceName: %v", err)
	}
	name, err := s.GetDeviceName()
	if err != nil {
		t.Fatalf("GetDeviceName: %v", err)
	}
	if name != "My Mac Pro" {
		t.Errorf("expected 'My Mac Pro', got %q", name)
	}
}
